---
title: "R Notebook"
author: yaoan
date: 7/27/2022
output: html_notebook
---

```{r, warning = F, message = F}
library(dplyr)
library(feather)
library(AER)
library(stargazer)
m_list <- list("power", "tiller", "seeder", "harvester", "corn", "dryer")


# load outcome data
top_cities <- c(3100,1100,4400,4403,5101,5000,3301,4201,3205,6101,3201,4301,1200,4101,4419,3702,5301,3302,3401,4406,2101,3202,3502,2102) # Cities to exclude, top tier cities by https://news.cctv.com/2023/05/30/ARTI5kyAHUzgByGH08lUpEQ4230530.shtml
            # Shanghai, Beijing, Guangzhou, Shenzhen, Chengdu,Chongqin, Hangzhou, Wuhan, Suzhou, Xi'an, Nanjing, Changsha, Tianjin, Zhengzhou, Dongguan, Qingdao, Kunming, Ningbo, Hefei, Foshan, Shenyang, Wuxi, Xiamen, Dalian
employment_county <- arrow::read_feather(paste0("dataprocessing/output/employment_county.feather")) %>%
                      select(adcode, year, nonag, industrial_firms) %>%
                      plm::make.pbalanced(., index = c("adcode", "year")) %>% # make it balanced so the lag is correctly missing when there is a gap in time
                      group_by(adcode) %>%
                      arrange(adcode, year) %>%
                      mutate(nonag_fd = nonag -  dplyr::lag(nonag),
                             industrial_firms_fd = industrial_firms - dplyr::lag(industrial_firms),
                             industrial_firms_lag = dplyr::lag(industrial_firms),
                             industrial_firms_lag_fd = industrial_firms_lag -dplyr::lag(industrial_firms_lag),) %>%
                      mutate(city_code = substring(adcode, 0,4)) %>%
                      filter(! city_code %in% top_cities)
```
```{r prepare-data, warning = F, message = F}
for (m in 1:6){
  # Load province level machinery subsidy data
  shock <- arrow::read_feather(paste0("dataprocessing/output/", m_list[[m]], "/shock.feather")) %>%
    mutate(prv_size = paste(prv_code, "-", size)) %>%
    plm::make.pbalanced(., index = c("prv_size", "year")) %>% # make it balanced so the lag is correctly missing when there is a gap in time
    group_by(prv_size) %>%
    arrange(prv_size, year) %>%
    mutate(subsidy = subsidy/1000,
           subsidy_fd = subsidy - dplyr::lag(subsidy)) %>%
    select(prv_code, prv_size, year, size, subsidy, retail_price, subsidy_rate, subsidy_fd)

  # load county level machinery purchase data
  county_year <- arrow::read_feather(paste0("dataprocessing/output/", m_list[[m]], "/county_year.feather"))%>%
    plm::make.pbalanced(., index = c("adcode", "year")) %>% # make it balanced so the lag is correctly missing when there is a gap in time
    group_by(adcode) %>%
    arrange(adcode, year) %>%
    mutate(purchase_fd = purchase - dplyr::lag(purchase)) %>%
    select(adcode, year, purchase, purchase_fd)

  # Load county-size level shares
  county_year_size_shares <- arrow::read_feather(paste0("dataprocessing/output/", m_list[[m]], "/county_year_size_shares.feather"))

  reg_data <- county_year_size_shares %>%
    mutate(prv_code = substring(adcode, 0,2))%>%
    merge(shock, by = c("prv_code", "year", "size"), all.x = TRUE) %>%
    mutate(exposure_share_L1 = share_L1 * subsidy,
           exposure_share_L1_fd = share_L1 * subsidy_fd)%>%
    group_by(adcode, year) %>%
    summarise(ssiv_share_L1 = sum(exposure_share_L1, na.rm=T),
              ssiv_share_L1_fd = sum(exposure_share_L1_fd, na.rm=T),
                sum_shares_L1 = sum(share_L1[subsidy>0], na.rm = T), NAshares = sum(share_L1, na.rm = T))  %>% # sum of the shares of sizes with positive subsidy
    mutate(ssiv_share_L1 = replace(ssiv_share_L1, NAshares ==0, NA),
           ssiv_share_L1_fd = replace(ssiv_share_L1_fd, NAshares ==0, NA)) %>%
    merge(county_year, by = c("adcode", "year"), all.x = T, all.y = T) %>%
    merge(employment_county, by = c("adcode", "year")) %>%
    mutate(year = as.factor(year)) %>%
    filter(!if_any(c(nonag_fd, purchase_fd, ssiv_share_L1_fd), is.na)) %>% distinct(adcode, year,  .keep_all = T)


  ols <-   lfe::felm(nonag ~ 1 + purchase | 0 | 0| adcode , data= reg_data )
  tsls <- lfe::felm(nonag ~ 1  | 0 | (purchase ~ ssiv_share_L1)| adcode , data= reg_data ) # 2SLS
  tsls_tfe <- lfe::felm(nonag ~ 1  | year | (purchase ~ ssiv_share_L1)| adcode , data= reg_data ) # 2SLS with time FE
  tsls_tfefd <- lfe::felm(nonag_fd ~ 1  | year | (purchase_fd  ~ ssiv_share_L1_fd )| adcode , data= reg_data )# 2SLS with time FE and FD
  fal <- lfe::felm(industrial_firms_lag_fd ~ 1 + ssiv_share_L1_fd | year | 0| adcode , data= reg_data ) # Falsification test
  reg_obs <- reg_data %>% select(adcode, year)

  # Store the regression results
  assign(m_list[[m]], list(ols = ols,
                           tsls = tsls,
                           tsls_tfe = tsls_tfe,
                           tsls_tfefd = tsls_tfefd,
                           fal = fal,
                           reg_obs = reg_obs))

}
```
```{r}
benchmark_reg_obs <- power$reg_obs
save(benchmark_reg_obs, file = "regression/input/bechmark_reg_obs_county.RData")

```

# Assemble county level falsification test results by machinery type into stargazer tables
```{r}
fal_county <- stargazer(power$fal, tiller$fal, seeder$fal, harvester$fal, corn$fal, dryer$fal,
                       title = "Falsification test results",
                       align = TRUE,
                       out = "regression/output/fal_county.html",
                       out.header = TRUE,
                       column.labels = c("Tractor", "Rotary tiller",  "Seeder,transplanter", "Grain harvester", "Corn harvester", "Grain dryer"),
                       dep.var.caption = 'Dependent variable: Number of industrial firms in the previous year',
                       dep.var.labels.include = F,
                       covariate.labels = c("Shift-Share IV"),
                       omit = c("Constant"),
                       ci = FALSE,
                       label = "fal_county",
                       font.size = "Huge",
                       df = FALSE)
```
# Assemble county level 2SLS first stage results by machinery type into stargazer tables
```{r}
fs_county_tfefd <- stargazer(power$tsls_tfefd$stage1, tiller$tsls_tfefd$stage1, seeder$tsls_tfefd$stage1, harvester$tsls_tfefd$stage1, corn$tsls_tfefd$stage1, dryer$tsls_tfefd$stage1,
                                 title = "First stage estimation results by machinery types - county level",
                                 align = TRUE,
                                out = "regression/output/fs_county_tfefd.html",
                                 out.header = TRUE,
                                 dep.var.labels = c("Tractor", "Rotary tiller",  "Seeder,transplanter", "Grain harvester", "Corn harvester", "Grain dryer"),
                                 dep.var.caption  = 'Dependent variable: Machinery purchase (in 1000)',
                                 column.labels = c("Horsepower",
                                                     "Width (m)",
                                                     "Rows",
                                                     "Speed (kg/s)",
                                                     "Rows",
                                                     "Capacity (ton/day)"),
                                 covariate.labels = c('Shift-share IV = market shares $\\times$ subsidy (1000 yuan)'),
                                 omit = c("Constant"),
                                 ci = FALSE,
                                 label = "fs_county_tfefd",
                                font.size = "Huge",
                                 df = FALSE,
                                  add.lines = list(c("Montiel-Pflueger robust F stat. for weak instrument",
                                                     formatC(power$tsls_tfefd$stage1$rob.iv1fstat$purchase_fd[5], digits = 3, format = "f"),
                                                      formatC(tiller$tsls_tfefd$stage1$rob.iv1fstat$purchase_fd[5], digits = 3, format = "f"),
                                                      formatC(seeder$tsls_tfefd$stage1$rob.iv1fstat$purchase_fd[5], digits = 3, format = "f"),
                                                      formatC(harvester$tsls_tfefd$stage1$rob.iv1fstat$purchase_fd[5], digits = 3, format = "f"),
                                                      formatC(corn$tsls_tfefd$stage1$rob.iv1fstat$purchase_fd[5], digits = 3, format = "f"),
                                                      formatC(dryer$tsls_tfefd$stage1$rob.iv1fstat$purchase_fd[5]), digits = 3, format = "f")
                                                    )

)

```
```{r}
# adjustbox so it fits the page width

fs_county_tfefd <- append(fs_county_tfefd, "\\begin{adjustbox}{width={1.2\\textwidth},totalheight={\\textheight},keepaspectratio,center}", after = grep("label", fs_county_tfefd)[1])
fs_county_tfefd <- append(fs_county_tfefd, "\\end{adjustbox} \\end{center}", after = grep("tabular", fs_county_tfefd)[2])

# edit dependent variable labels. stargazer thinks there is only one dep var becauses all the regressions has nonag_fd as lhs.
fs_county_tfefd[grepl('Tractor', fs_county_tfefd)] <- "& \\multicolumn{1}{c}{Tractor} & \\multicolumn{1}{c}{Rotary tiller} & \\multicolumn{1}{c}{Seeder,transplanter} & \\multicolumn{1}{c}{Grain harvester} & \\multicolumn{1}{c}{Corn harvester} & \\multicolumn{1}{c}{Grain dryer} \\\\"

# add footnote
fs_county_tfefd[grepl('\\centering', fs_county_tfefd)] <- "\\begin{table}[!htbp]\\begin{center}"
fs_county_tfefd[grepl('Note', fs_county_tfefd)] <- ""
notes <- "\\footnotesize{\\textit{Notes:} This table reports the first stage estimates of the shift-share instrumental variable with county level data in year 2015 - 2019 from China. The shift-share instrumental variable measures the city's exposure to the machinery subsidy policy depending on the market shares in the previous year. The endogenous variable is the subsidized machinery purchase. The reported standard errors in the parenthesis are
heteroskedasticity-robust and are clustered at the city level. The county fixed effects are included by first-differencing the variables and the shocks, as suggested by Borusyak et al. (2022). The year fixed effects are included using dummy variables. Counties in 24 top tier cities are dropped.
$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01.}"
fs_county_tfefd <- append(fs_county_tfefd, notes, after = grep('center', fs_county_tfefd)[3] )

write(fs_county_tfefd,file = paste0("communicating/tables/fs_county_tfefd.tex"))
```



# Assemble county level 2SLS second stage results by machinery type into stargazer tables
```{r}
ss_county_tfefd <- stargazer(power$tsls_tfefd, tiller$tsls_tfefd, seeder$tsls_tfefd, harvester$tsls_tfefd, corn$tsls_tfefd, dryer$tsls_tfefd,
                                 title  = "2SLS estimation results for the effect of mechanization on employment by machinery types - county level",
                                 align = TRUE,
                                out = "regression/output/ss_county_tfefd.html",
                                 out.header = TRUE,
                                 dep.var.labels = c("Tractor", "Rotary tiller",  "Seeder,transplanter", "Grain harvester", "Corn harvester", "Grain dryer"),
                                 dep.var.caption  = 'Dependent variable: Non-agricultural employment (1000 people)',
                                 column.labels = c("Horsepower",
                                                     "Width (m)",
                                                     "Rows",
                                                     "Speed (kg/s)",
                                                     "Rows",
                                                     "Capacity (ton/day)"),
                                 covariate.labels = c("Machinery purchase (in 1000)"),
                                 omit = c("Constant"),
                                 ci = FALSE,
                                 label = "ss_county_tfefd",
                                font.size = "Huge",
                                 df = FALSE,
                                 omit.stat = c("f", "rsq"),
                                  add.lines = list(c("F stat for weak instrument",
                                                     formatC(power$tsls_tfefd$stage1$rob.iv1fstat$purchase_fd[5], digits = 3, format = "f"),
                                                      formatC(tiller$tsls_tfefd$stage1$rob.iv1fstat$purchase_fd[5], digits = 3, format = "f"),
                                                      formatC(seeder$tsls_tfefd$stage1$rob.iv1fstat$purchase_fd[5], digits = 3, format = "f"),
                                                      formatC(harvester$tsls_tfefd$stage1$rob.iv1fstat$purchase_fd[5], digits = 3, format = "f"),
                                                      formatC(corn$tsls_tfefd$stage1$rob.iv1fstat$purchase_fd[5], digits = 3, format = "f"),
                                                      formatC(dryer$tsls_tfefd$stage1$rob.iv1fstat$purchase_fd[5]), digits = 3, format = "f")
                                                    )

)
```

```{r}
# adjustbox so it fits the page width
ss_county_tfefd <- append(ss_county_tfefd, "\\begin{adjustbox}{width={1.2\\textwidth},totalheight={\\textheight},keepaspectratio,center}", after = grep("label", ss_county_tfefd)[1])
ss_county_tfefd <- append(ss_county_tfefd, "\\end{adjustbox} \\end{center}", after = grep("tabular", ss_county_tfefd)[2])

# edit dependent variable labels. stargazer thinks there is only one dep var becauses all the regressions has nonag_fd as lhs.
ss_county_tfefd[grepl('Tractor', ss_county_tfefd)] <- "& \\multicolumn{1}{c}{Tractor} & \\multicolumn{1}{c}{Rotary tiller} & \\multicolumn{1}{c}{Seeder,transplanter} & \\multicolumn{1}{c}{Grain harvester} & \\multicolumn{1}{c}{Corn harvester} & \\multicolumn{1}{c}{Grain dryer} \\\\"
# add footnote
ss_county_tfefd[grepl('\\centering', ss_county_tfefd)] <- "\\begin{table}[!htbp]\\begin{center}"
ss_county_tfefd[grepl('Note', ss_county_tfefd)] <- ""
notes <- "\\footnotesize{\\textit{Notes:} This table reports the two-stage least squares estimates on the effect of subsidized machinery purchase on  employment in all secondary and tertiary sectors with county level data in year 2015 - 2019 from China. The shift-share instrumental variable measures the county's exposure to the machinery subsidy policy depending on the market shares in the previous year. The endogenous variable is the subsidized machinery purchase. The reported standard errors in the parenthesis are
heteroskedasticity-robust and are clustered at the county level. The fixed effects are included by first-differencing the variables and the shocks, as suggested by Borusyak et al. (2022).
$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01.}"
ss_county_tfefd <- append(ss_county_tfefd, notes, after = grep('center', ss_county_tfefd)[3] )

write(ss_county_tfefd, file = paste0("communicating/tables/ss_county_tfefd.tex"))


```

# Only export the 2SLS second stage result for tractors, later combine it with Stata results




